import { buildIndex } from '../core/index'

const PARAGRAPH_SEPARATOR = '\n\n'

const PARAGRAPH_TEXTS: readonly string[] = [
    'Solar energy is one of the most important renewable energy sources in the modern world. A solar system uses sunlight to produce electricity or heat. The basic idea is simple: sunlight reaches a solar panel, the panel converts part of that sunlight into electrical energy, and the electrical system delivers that energy to the loads that need it.',

    'انرژی خورشیدی یکی از مهم‌ترین منابع انرژی تجدیدپذیر در جهان امروز است. یک سیستم خورشیدی می‌تواند از نور خورشید برق یا گرما تولید کند. ایده اصلی ساده است: نور خورشید به پنل خورشیدی می‌رسد، پنل بخشی از این نور را به انرژی الکتریکی تبدیل می‌کند و سیستم الکتریکی این انرژی را به بارهایی که به آن نیاز دارند منتقل می‌کند.',

    'A photovoltaic, or PV, system is designed to convert sunlight directly into electricity. Solar cells inside a PV panel are made from semiconductor materials. When photons from sunlight reach these cells, they transfer energy to electrons and create an electric current. Many individual solar cells are connected together to form a solar panel, and several panels can be connected to form a larger solar array.',

    'سیستم فتوولتائیک یا PV برای تبدیل مستقیم نور خورشید به برق طراحی شده است. سلول‌های خورشیدی داخل یک پنل فتوولتائیک از مواد نیمه‌رسانا ساخته می‌شوند. هنگامی که فوتون‌های نور خورشید به سلول‌ها برخورد می‌کنند، انرژی خود را به الکترون‌ها منتقل کرده و جریان الکتریکی ایجاد می‌کنند. چندین سلول خورشیدی در کنار یکدیگر یک پنل را تشکیل می‌دهند و چند پنل می‌توانند یک آرایه خورشیدی بزرگ‌تر بسازند.',

    'The amount of energy produced by a solar panel depends on several factors. Solar radiation, panel orientation, panel angle, temperature, shading, dust, and the electrical characteristics of the system all affect production. A panel usually produces more energy when it receives strong direct sunlight and has a suitable orientation toward the sun.',

    'مقدار انرژی تولیدشده توسط یک پنل خورشیدی به عوامل مختلفی بستگی دارد. میزان تابش خورشیدی، جهت قرارگیری پنل، زاویه پنل، دما، سایه، گرد و غبار و مشخصات الکتریکی سیستم همگی بر تولید انرژی تأثیر می‌گذارند. معمولاً زمانی که پنل نور مستقیم و مناسب دریافت کند و جهت آن نسبت به خورشید درست باشد، انرژی بیشتری تولید خواهد کرد.',

    'The solar inverter is another important part of a photovoltaic system. Solar panels normally produce DC electricity, while most household and commercial electrical equipment uses AC electricity. The inverter converts DC power into AC power and can also monitor the electrical performance of the solar system.',

    'اینورتر خورشیدی یکی از مهم‌ترین اجزای یک سیستم فتوولتائیک است. پنل‌های خورشیدی معمولاً برق DC تولید می‌کنند، در حالی که بیشتر تجهیزات الکتریکی خانگی و تجاری از برق AC استفاده می‌کنند. اینورتر توان DC را به AC تبدیل می‌کند و در بسیاری از سیستم‌ها وظیفه پایش عملکرد الکتریکی سیستم خورشیدی را نیز بر عهده دارد.',

    'In a grid-connected solar system, electricity generated by the panels can be used directly by local loads. If the solar system produces more electricity than the loads need, the extra energy can be sent to the electrical grid when the installation and local regulations allow it. When solar production is lower than demand, electricity can be supplied by the grid.',

    'در یک سیستم خورشیدی متصل به شبکه، برق تولیدشده توسط پنل‌ها می‌تواند مستقیماً توسط بارهای محلی مصرف شود. اگر سیستم خورشیدی بیشتر از مقدار مورد نیاز بار برق تولید کند، در صورت وجود زیرساخت و قوانین مناسب، انرژی اضافی می‌تواند به شبکه برق ارسال شود. زمانی که تولید خورشیدی کمتر از مصرف باشد، انرژی مورد نیاز می‌تواند از شبکه تأمین شود.',

    'An off-grid solar system works differently. It is designed to operate without a permanent connection to the electrical grid. Batteries are usually an important part of this type of system because solar panels do not produce electricity at night. During sunny hours, part of the energy can power the loads while another part can charge the batteries.',

    'سیستم خورشیدی مستقل از شبکه یا Off-Grid به شکل متفاوتی کار می‌کند. این سیستم برای کارکردن بدون اتصال دائمی به شبکه برق طراحی شده است. باتری معمولاً یکی از اجزای مهم این نوع سیستم است، زیرا پنل‌های خورشیدی در طول شب برق تولید نمی‌کنند. در ساعات آفتابی، بخشی از انرژی می‌تواند برای مصرف بارها استفاده شود و بخش دیگری باتری‌ها را شارژ کند.',

    'Battery storage allows a solar system to save electrical energy for later use. During the day, when solar production is high, the battery can store energy. At night or during periods of low solar radiation, the stored energy can be supplied to electrical loads. The battery capacity must be selected according to the required energy, expected backup time, and system design.',

    'ذخیره‌سازی انرژی با باتری به سیستم خورشیدی اجازه می‌دهد انرژی الکتریکی را برای استفاده در زمان دیگری ذخیره کند. در طول روز و زمانی که تولید خورشیدی زیاد است، باتری می‌تواند انرژی را ذخیره کند. در شب یا زمان‌هایی که تابش خورشید کم است، انرژی ذخیره‌شده می‌تواند برای تأمین بارهای الکتریکی استفاده شود. ظرفیت باتری باید بر اساس انرژی مورد نیاز، مدت زمان پشتیبانی و طراحی سیستم انتخاب شود.',

    'Before designing a solar system, the electrical loads should be analyzed carefully. A designer usually starts by creating a list of electrical devices, their power in watts, and the number of hours they operate each day. Daily energy consumption can then be estimated in kilowatt-hours. Peak load and average load are also important for selecting the inverter and other electrical equipment.',

    'قبل از طراحی یک سیستم خورشیدی، باید بارهای الکتریکی با دقت بررسی شوند. معمولاً طراحی با تهیه فهرستی از تجهیزات الکتریکی، توان هر وسیله بر حسب وات و تعداد ساعات کارکرد روزانه شروع می‌شود. سپس می‌توان انرژی مصرفی روزانه را بر حسب کیلووات‌ساعت محاسبه کرد. بار اوج و بار متوسط نیز برای انتخاب اینورتر و سایر تجهیزات الکتریکی اهمیت زیادی دارند.',

    'Solar radiation is not the same everywhere. Geographic location, latitude, season, weather, clouds, and atmospheric conditions affect the amount of sunlight available to a solar system. For this reason, solar system design should use appropriate solar radiation data for the installation location. Good resource assessment can make the system smaller, more reliable, and more economical.',

    'تابش خورشیدی در همه مکان‌ها یکسان نیست. موقعیت جغرافیایی، عرض جغرافیایی، فصل، وضعیت آب‌وهوا، ابرها و شرایط جوی بر مقدار نور خورشیدی قابل استفاده برای سیستم تأثیر می‌گذارند. به همین دلیل در طراحی سیستم خورشیدی باید از اطلاعات مناسب تابش خورشیدی مربوط به محل نصب استفاده شود. بررسی درست منابع خورشیدی می‌تواند باعث شود سیستم اندازه مناسب‌تر، قابل‌اعتمادتر و اقتصادی‌تری داشته باشد.',

    'The orientation and tilt of solar panels are important because the angle of sunlight changes during the day and throughout the year. A fixed solar installation is normally designed to receive as much useful radiation as possible during the expected operating period. Some systems use tracking mechanisms that move the panels to follow the sun, but tracking adds mechanical complexity and maintenance requirements.',

    'جهت و زاویه نصب پنل‌های خورشیدی اهمیت زیادی دارند، زیرا زاویه تابش نور خورشید در طول روز و در فصل‌های مختلف تغییر می‌کند. یک سیستم ثابت معمولاً به شکلی طراحی می‌شود که در دوره مورد نظر بیشترین تابش مفید را دریافت کند. برخی سیستم‌ها از مکانیزم‌های ردیاب خورشیدی استفاده می‌کنند که پنل‌ها را برای دنبال کردن خورشید حرکت می‌دهد، اما ردیاب باعث افزایش پیچیدگی مکانیکی و نیاز به نگهداری می‌شود.',

    'Shading can significantly reduce solar production. Even when most of a panel is receiving sunlight, a shaded section can affect the electrical output of cells connected in the same circuit. Trees, buildings, antennas, nearby structures, and other panels should therefore be considered during site analysis. Good planning reduces shading losses and improves the performance of the solar system.',

    'سایه می‌تواند تولید انرژی خورشیدی را به میزان قابل توجهی کاهش دهد. حتی اگر بیشتر سطح یک پنل در معرض نور خورشید باشد، یک قسمت سایه‌دار می‌تواند بر خروجی الکتریکی سلول‌های متصل در همان مدار تأثیر بگذارد. بنابراین در بررسی محل نصب باید درخت‌ها، ساختمان‌ها، آنتن‌ها، سازه‌های اطراف و حتی پنل‌های دیگر مورد توجه قرار گیرند. طراحی مناسب باعث کاهش تلفات سایه و افزایش عملکرد سیستم خورشیدی می‌شود.',

    'Solar panels also have electrical limits such as voltage, current, and maximum power. Panels are commonly connected in series to increase voltage or in parallel to increase current. The final configuration must be compatible with the inverter and other components. Incorrect electrical sizing can reduce efficiency or even damage equipment.',

    'پنل‌های خورشیدی دارای محدودیت‌های الکتریکی مانند ولتاژ، جریان و توان بیشینه هستند. پنل‌ها معمولاً برای افزایش ولتاژ به صورت سری و برای افزایش جریان به صورت موازی متصل می‌شوند. پیکربندی نهایی باید با اینورتر و سایر تجهیزات سازگار باشد. انتخاب نادرست مشخصات الکتریکی می‌تواند باعث کاهش راندمان یا حتی آسیب به تجهیزات شود.',

    'Energy efficiency is also important when designing a solar system. Reducing unnecessary electricity consumption can reduce the required size and cost of the photovoltaic system. Efficient lighting, efficient motors, better insulation, and smart control systems can reduce the total energy demand before additional solar panels or batteries are installed.',

    'بهره‌وری انرژی نیز در طراحی سیستم خورشیدی اهمیت دارد. کاهش مصرف غیرضروری برق می‌تواند اندازه و هزینه مورد نیاز سیستم فتوولتائیک را کاهش دهد. استفاده از روشنایی کم‌مصرف، موتورهای با راندمان مناسب، عایق‌کاری بهتر و سیستم‌های کنترل هوشمند می‌تواند قبل از افزایش تعداد پنل‌ها یا باتری‌ها، میزان تقاضای کل انرژی را کاهش دهد.',

    'A complete solar installation may contain solar panels, mounting structures, DC cables, protection devices, an inverter, AC protection, monitoring equipment, and sometimes batteries. Each component has a specific role. The system should be designed as one complete electrical system rather than selecting each component independently.',

    'یک نیروگاه یا سیستم خورشیدی کامل می‌تواند شامل پنل‌های خورشیدی، سازه نگهدارنده، کابل‌های DC، تجهیزات حفاظتی، اینورتر، تجهیزات حفاظتی AC، تجهیزات مانیتورینگ و در برخی موارد باتری باشد. هر کدام از این اجزا وظیفه مشخصی دارند. سیستم باید به صورت یک مجموعه الکتریکی کامل طراحی شود و نباید هر قطعه بدون توجه به سایر اجزا به صورت مستقل انتخاب شود.',

    'Monitoring helps the operator understand how a solar system is performing. Modern inverters can provide information about voltage, current, power, daily energy, monthly energy, and system faults. Monitoring can also help identify unexpected drops in production. For example, a sudden reduction in energy may indicate shading, dirt, equipment failure, or another problem.',

    'سیستم مانیتورینگ به بهره‌بردار کمک می‌کند عملکرد سیستم خورشیدی را بررسی کند. اینورترهای مدرن می‌توانند اطلاعاتی مانند ولتاژ، جریان، توان، انرژی روزانه، انرژی ماهانه و خطاهای سیستم را نمایش دهند. مانیتورینگ همچنین می‌تواند به شناسایی کاهش غیرمنتظره تولید کمک کند. برای مثال، کاهش ناگهانی انرژی ممکن است نشانه سایه، کثیفی، خرابی تجهیزات یا مشکل دیگری باشد.',

    'The main goal of solar system design is not simply to install as many panels as possible. The goal is to match solar generation with energy demand, available solar radiation, electrical equipment, physical space, safety requirements, and economic constraints. A well-designed system balances energy production, reliability, cost, and maintainability.',

    'هدف اصلی طراحی یک سیستم خورشیدی فقط نصب بیشترین تعداد پنل ممکن نیست. هدف این است که تولید انرژی خورشیدی با میزان مصرف، تابش موجود، تجهیزات الکتریکی، فضای نصب، الزامات ایمنی و محدودیت‌های اقتصادی هماهنگ شود. یک سیستم خوب باید بین تولید انرژی، قابلیت اطمینان، هزینه و امکان نگهداری تعادل مناسبی ایجاد کند.',

    'In simple terms, the complete process can be understood as a chain: sunlight reaches the solar panels, the photovoltaic cells generate DC electricity, the inverter manages or converts the electrical power, and the energy is finally delivered to loads, batteries, or the electrical grid. Every part of this chain affects the final performance of the solar system.',

    'به زبان ساده، کل فرآیند را می‌توان به صورت یک زنجیره در نظر گرفت: نور خورشید به پنل‌های خورشیدی می‌رسد، سلول‌های فتوولتائیک برق DC تولید می‌کنند، اینورتر توان الکتریکی را مدیریت یا تبدیل می‌کند و در نهایت انرژی به بارها، باتری‌ها یا شبکه برق منتقل می‌شود. هر بخش از این زنجیره بر عملکرد نهایی سیستم خورشیدی تأثیر می‌گذارد.',

    'The future of solar energy is closely connected to energy storage, smart grids, electric vehicles, and better power electronics. As solar technology becomes more efficient and affordable, photovoltaic systems can play a larger role in reducing dependence on fossil fuels and increasing the share of renewable energy in the electricity system.',

    'آینده انرژی خورشیدی ارتباط نزدیکی با ذخیره‌سازی انرژی، شبکه‌های هوشمند، خودروهای برقی و تجهیزات الکترونیک قدرت پیشرفته دارد. با افزایش راندمان و کاهش هزینه فناوری خورشیدی، سیستم‌های فتوولتائیک می‌توانند نقش بزرگ‌تری در کاهش وابستگی به سوخت‌های فسیلی و افزایش سهم انرژی‌های تجدیدپذیر در سیستم برق داشته باشند.',
]

export interface Paragraph {
    id: string
    text: string
    start: number
    end: number
}

function layoutParagraphs(texts: readonly string[]): Paragraph[] {
    let offset = 0

    return texts.map((text, i) => {
        const paragraph: Paragraph = {
            id: `p${i + 1}`,
            text,
            start: offset,
            end: offset + text.length,
        }
        offset = paragraph.end + PARAGRAPH_SEPARATOR.length
        return paragraph
    })
}

export const PARAGRAPHS: readonly Paragraph[] = layoutParagraphs(PARAGRAPH_TEXTS)

export const FULL_TEXT: string = PARAGRAPH_TEXTS.join(PARAGRAPH_SEPARATOR)

export const SEARCH_INDEX = buildIndex(PARAGRAPH_TEXTS)
